(TeX-add-style-hook "builtin"
 (lambda ()
    (LaTeX-add-index-entries
     "streams"
     "aliases!streams"
     "aliases!streams!user\\_input"
     "aliases!streams!user\\_output"
     "aliases!streams!user\\_error"
     "aliases!streams!user\\_warning"
     "aliases!streams!user\\_message"
     "streams!system"
     "streams!STDDBG"
     "streams!STDERR"
     "streams!STDFDBK"
     "streams!STDIN"
     "streams!STDOUT"
     "streams!STDWARN"
     "streams!STDMSG"
     "Unicode!UTF-8"
     "character sets"
     "CP1252"
     "LATIN-1"
     "attributed variables"
     "Prolog flags!{\\tt write\\_attributes}"
     "canonical format"
     "Prolog flags!{\\tt warning\\_action}"
     "\\texttt{fmt\\_read/4}"
     "\\texttt{read\\_line/2}"
     "\\texttt{fmt\\_write/2}"
     "Prolog flags!{\\tt exception\\_action}"
     "\\^\\ /2"
     "control"
     "cut"
     "$\\backslash$\\texttt{+/1}"
     "floundering"
     "\\texttt{->/2}"
     "term depth!definition"
     "terms!cyclic"
     "term size!definition"
     "interned terms"
     "occurs check"
     "Prolog flags!{\\tt max\\_table\\_subgoal\\_depth}"
     "Prolog flags!{\\tt max\\_answer\\_term\\_depth}"
     "Prolog flags!{\\tt max\\_answer\\_list\\_depth}"
     "Prolog flags!{\\tt max\\_table\\_subgoal\\_action}"
     "Prolog flags!{\\tt max\\_answer\\_term\\_action}"
     "Prolog flags!{\\tt max\\_answer\\_list\\_action}"
     "Prolog flags!{\\tt unify\\_with\\_occurs\\_check}"
     "Silk"
     "Flora-2"
     "tries!depth limit"
     "garbage collection!atoms"
     "Prolog flags!{\\tt atom\\_garbage\\_collection}"
     "sets, bags"
     "aggregate predicates!prolog"
     "\\^"
     "\\texttt{\"!/0}"
     "tripwires!timed call")
    (LaTeX-add-labels
     "standard"
     "sec:types"
     "sec:IO-streams"
     "sec-charsets"
     "Arithmetic"
     "sec:arith-eval"
     "Convenience"
     "sec:control"
     "tnot/1"
     "MetaLogical"
     "sec:cyclic"
     "tfindall/3"
     "meta_predicates"
     "sec:timed-call")
    (TeX-run-style-hooks
     "comparison")))

