(TeX-add-style-hook "state"
 (lambda ()
    (LaTeX-add-index-entries
     "state of the system"
     "system, state of"
     "predicate indicator"
     "term indicator"
     "Prolog-commons"
     "Prolog flags"
     "Prolog flags!{\\tt bounded}"
     "Prolog flags!{\\tt min\\_integer}"
     "Prolog flags!{\\tt max\\_integer}"
     "Prolog flags!{\\tt integer\\_rounding\\_function}"
     "Prolog flags!{\\tt debug}"
     "Prolog flags!{\\tt unknown}"
     "Prolog flags!{\\tt double\\_quotes}"
     "Prolog flags!{\\tt dialect}"
     "Prolog flags!{\\tt version\\_data}"
     "Unknown predicate handling"
     "Prolog flags!{\\tt backtrace\\_on\\_error}"
     "Prolog flags!{\\tt dcg\\_style}"
     "Prolog flags!{\\tt heap\\_garbage\\_collection}"
     "Prolog flags!{\\tt heap\\_margin}"
     "Prolog flags!{\\tt clause\\_garbage\\_collection}"
     "Prolog flags!{\\tt atom\\_garbage\\_collection}"
     "Prolog flags!{\\tt table\\_gc\\_action}"
     "Prolog flags!{\\tt goal}"
     "streams!STDERR"
     "garbage collection"
     "Prolog flags!{\\tt tracing}"
     "Prolog flags!{\\tt warning\\_action}"
     "Prolog flags!{\\tt write\\_depth}"
     "Prolog flags!{\\tt write\\_attributes}"
     "attributed variables"
     "Prolog flags!{\\tt unify\\_with\\_occurs\\_check}"
     "occurs check"
     "terms!cyclic"
     "Prolog flags!{\\tt character\\_set}"
     "character sets"
     "Prolog flags!{\\tt errors\\_with\\_position}"
     "errors with position"
     "Prolog flags!{\\tt exception\\_action}"
     "Prolog flags!{\\tt exception\\_pre\\_action}"
     "tabling!and exceptions"
     "Prolog flags!{\\tt max\\_tab\\_usage}"
     "tripwires"
     "term size"
     "Prolog flags!{\\tt max\\_table\\_subgoal\\_size}"
     "Prolog flags!{\\tt max\\_table\\_subgoal\\_size\\_action}"
     "Prolog flags!{\\tt max\\_incomplete\\_subgoals}"
     "Prolog flags!{\\tt max\\_incomplete\\_subgoals\\_action}"
     "Prolog flags!{\\tt max\\_scc\\_subgoals}"
     "Prolog flags!{\\tt max\\_scc\\_subgoals\\_action}"
     "termination!subgoal abstraction"
     "termination!radial restraint"
     "Prolog flags!{\\tt max\\_table\\_answer\\_size}"
     "Prolog flags!{\\tt max\\_table\\_answer\\_size\\_action}"
     "Prolog flags!{\\tt max\\_answers\\_for\\_subgoal}"
     "Prolog flags!{\\tt max\\_answers\\_for\\_subgoal\\_action}"
     "Prolog flags!{\\tt max\\_memory}"
     "Prolog flags!{\\tt thread\\_glsize}"
     "Prolog flags!{\\tt thread\\_tcpsize}"
     "Prolog flags!{\\tt thread\\_complsize}"
     "Prolog flags!{\\tt thread\\_pdlsize}"
     "Prolog flags!{\\tt thread\\_detached}"
     "Prolog flags!{\\tt max\\_threads}"
     "Prolog flags!{\\tt max\\_queue\\_size}"
     "Prolog flags!{\\tt shared\\_predicates}"
     "shared\\_predicates"
     "tabling!call subsumption"
     "tabling!call variance"
     "tabling!answer subsumption"
     "tabling!incremental"
     "garbage collection!heap"
     "tabled subgoals!incomplete"
     "Incremental Dependency Graph (IDG)"
     "Prologs!SWI"
     "Prologs!YAP")
    (LaTeX-add-labels
     "State"
     "prolog-flags"
     "PredProp"
     "environmental")))

